# -*- coding: utf-8 -*-
"""oilsplitdetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pWF5sxEUR6Sh4qMm0GgFYGW13Dxi7DsP
"""

!pip install -q transformers torch torchvision pillow rasterio geopandas shapely pyproj matplotlib

import os
import numpy as np
import torch
import matplotlib.pyplot as plt

from PIL import Image
from transformers import AutoImageProcessor, AutoModelForImageClassification

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Using device:", device)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

# Install Hugging Face Hub
!pip install -q huggingface_hub

# Import libraries
import torch
from huggingface_hub import hf_hub_download

# Set the Hugging Face model name
MODEL_NAME = "MeghanaK25/sar-oil-slick-detection"

# Download the PyTorch model
model_path = hf_hub_download(
    repo_id=MODEL_NAME,
    filename="model.pth"
)

# Print the downloaded model path
print("Model downloaded successfully!")
print(model_path)

# Load the PyTorch checkpoint
checkpoint = torch.load(
    model_path,
    map_location="cpu",
    weights_only=False
)

# Print the checkpoint type
print("Checkpoint type:", type(checkpoint))

# Print checkpoint keys if it is a dictionary
if isinstance(checkpoint, dict):
    print("Checkpoint keys:")
    for key in checkpoint.keys():
        print("→", key)
else:
    print("Checkpoint is not a dictionary.")

# Confirm Step 3 completion
print("Step 3 completed successfully!")

# Import PyTorch
import torch

# Check the checkpoint type
print("Checkpoint type:", type(checkpoint))

# Display checkpoint information
if isinstance(checkpoint, dict):
    print("\nCheckpoint keys:")
    for key, value in checkpoint.items():
        print(f"\nKey: {key}")
        print("Type:", type(value))

        # Display tensor information
        if isinstance(value, dict):
            print("Number of entries:", len(value))

            # Show first few entries
            for i, (subkey, subvalue) in enumerate(value.items()):
                print(" ", subkey, "→", type(subvalue))

                if i >= 4:
                    print("  ...")
                    break

        elif torch.is_tensor(value):
            print("Shape:", value.shape)

else:
    print("\nThe checkpoint itself is a PyTorch object:")
    print(checkpoint)

print(type(checkpoint))

if isinstance(checkpoint, dict):
    print("Checkpoint keys:")
    print(list(checkpoint.keys()))

# Import required libraries
import torch
import torch.nn as nn
from torchvision import models

# Select CPU or GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Create the ResNet-50 architecture
model = models.resnet50(weights=None)

# Change the final layer to two classes
model.fc = nn.Linear(
    model.fc.in_features,
    2
)

# Remove the "resnet." prefix from checkpoint keys
new_checkpoint = {}

for key, value in checkpoint.items():
    new_key = key.replace("resnet.", "", 1)
    new_checkpoint[new_key] = value

# Load the corrected checkpoint
model.load_state_dict(new_checkpoint)

# Move the model to GPU or CPU
model = model.to(device)

# Set model to evaluation mode
model.eval()

# Print confirmation
print("Model loaded successfully!")
print("Device:", device)
print("Architecture: ResNet-50")
print("Number of classes:", model.fc.out_features)

# Check whether any keys are missing
missing_keys, unexpected_keys = model.load_state_dict(
    new_checkpoint,
    strict=False
)

# Print the results
print("Missing keys:", missing_keys)
print("Unexpected keys:", unexpected_keys)

# Print the final layer
print(model.fc)

# Print the model device
print("Model device:", next(model.parameters()).device)

# Import required libraries
from google.colab import files
from PIL import Image
import torchvision.transforms as transforms
import torch
import matplotlib.pyplot as plt

# Upload a SAR image
uploaded = files.upload()

# Get the uploaded file name
image_path = list(uploaded.keys())[0]

# Open the image
image = Image.open(image_path).convert("RGB")

# Display image information
print("Image:", image_path)
print("Original size:", image.size)

# Define image preprocessing
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

# Preprocess the image
image_tensor = transform(image)

# Add batch dimension
image_tensor = image_tensor.unsqueeze(0)

# Move image to the same device as model
image_tensor = image_tensor.to(device)

# Display the image
plt.figure(figsize=(8, 8))
plt.imshow(image)
plt.axis("off")
plt.title("Uploaded SAR Image")
plt.show()

# Display tensor shape
print("Input tensor shape:", image_tensor.shape)

# Disable gradient calculation
with torch.no_grad():

    # Run the image through the model
    outputs = model(image_tensor)

    # Convert logits into probabilities
    probabilities = torch.softmax(outputs, dim=1)

# Get the predicted class
predicted_class = torch.argmax(probabilities, dim=1).item()

# Get confidence
confidence = probabilities[0, predicted_class].item()

# Display raw model output
print("Raw output:", outputs)
print("Probabilities:", probabilities)

print("\nPrediction class:", predicted_class)
print("Confidence:", f"{confidence * 100:.2f}%")

# Install dataset download utility
!pip install -q gdown